github_pat: "{{ lookup('env', 'GITHUB_PAT') | trim }}"
github_runner_owner: "lopezzuluagaj3-collab"
github_runner_repo: "polaris-kubernetes"
k3s_control_plane_ip: "{{ lookup('env', 'IP_PANEL') | trim }}"
k3s_proxy_ip: "{{ lookup('env', 'IP_PROXY') | trim }}"
aws_ebs_key_id: "{{ lookup('env', 'EBS_CSI_KEY_ID') | trim }}"
aws_ebs_access_key: "{{ lookup('env', 'EBS_CSI_ACCESS_KEY') | trim }}"