---
- name: 0. Configurar Nginx Proxy (Bastion)
  hosts: bastion
  become: true
  roles:
    - nginx_proxy

- name: 1. Configurar Control Plane de Kubernetes
  hosts: svr-airflow
  become: true
  roles:
    - k8s_master

- name: 2. Unir Nodos Workers al Clúster
  hosts: svr-rabbit:svr-celery-1:svr-celery-2:svr-db
  become: true
  roles:
    - k8s_worker

- name: 3. Instalar Tooling y Cilium CNI en el Control Plane
  hosts: svr-airflow
  become: true
  roles:
    - helm

- name: 4. Instalar EBS CSI Driver (StorageClass para PVCs)
  hosts: svr-airflow
  become: true
  roles:
    - ebs_csi_driver

- name: 5. Configurar GitHub Actions Runner
  hosts: svr-airflow
  become: true
  roles:
    - github_runner

- name: 6. Configurar Deploy Key para clonar el repo
  hosts: svr-airflow
  become: true
  roles:
    - deploy_key