---
- name: Instalar nodo Control Plane K3s (sin CNI por defecto)
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Obtener Token del clúster para los Worker Nodes
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_node_token

- name: Guardar Token en variable global de la sesión
  ansible.builtin.set_fact:
    cluster_token: "{{ k3s_node_token.content | b64decode | trim }}"

- name: Configurar permisos del kubeconfig para el usuario ubuntu
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copiar kubeconfig a la carpeta del usuario
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: '0600'
